-- Supabase SQL schema for Putry Agency social starter
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  full_name text,
  bio text,
  avatar_url text,
  role text default 'member',
  badge int default 1,
  banned boolean default false,
  updated_at timestamptz default now()
);

create table if not exists posts (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references profiles(id),
  created_at timestamptz default now()
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade,
  user_id uuid references profiles(id),
  content text,
  created_at timestamptz default now()
);

create table if not exists likes (
  id bigint generated by default as identity primary key,
  target_type text not null,
  target_id bigint not null,
  user_id uuid references profiles(id),
  created_at timestamptz default now()
);

create table if not exists recasts (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade,
  user_id uuid references profiles(id),
  created_at timestamptz default now()
);

create table if not exists follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references profiles(id),
  following_id uuid references profiles(id),
  created_at timestamptz default now(),
  unique(follower_id, following_id)
);

create table if not exists dm_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now()
);

create table if not exists dm_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint references dm_conversations(id) on delete cascade,
  user_id uuid references profiles(id),
  joined_at timestamptz default now(),
  unique(conversation_id, user_id)
);

create table if not exists dm_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references dm_conversations(id) on delete cascade,
  sender_id uuid references profiles(id),
  content text,
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  actor_id uuid references profiles(id),
  type text not null,
  reference_id bigint,
  data jsonb,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_notifications_user_is_read on notifications (user_id, is_read);
create index if not exists idx_dm_messages_conv_created on dm_messages (conversation_id, created_at);
